spring.application.name=orbitagro-api

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orbitagro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:orbitagro}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:orbitagro123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Server
server.port=${SERVER_PORT:8080}
