spring.application.name=orbitagro-api

server.port=${SERVER_PORT:8080}

# PostgreSQL (Docker Compose)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orbitagro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:orbitagro}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:orbitagro123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

# JWT
jwt.secret=${JWT_SECRET:orbitagro-secret-key-2026-fiap-global-solution-muito-segura}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
